[
  [
    "minecraft:soul_sand_valley",
    [],
    [],
    [
      "rankine:blueschist",
      "rankine:blueschist",
      "rankine:blueschist",
      "rankine:blueschist",
      "rankine:honeystone",
      "rankine:honeystone",
      "rankine:honeystone",
      "rankine:wehrlite"
    ],
    [],
    "rankine:dark_gravel",
    "minecraft:air",
    "minecraft:air"
  ],
  [
    "minecraft:basalt_deltas",
    [],
    [],
    [
      "minecraft:blackstone",
      "minecraft:blackstone",
      "minecraft:blackstone",
      "minecraft:blackstone",
      "minecraft:basalt",
      "minecraft:basalt",
      "minecraft:basalt",
      "rankine:dunite"
    ],
    [],
    "rankine:dark_gravel",
    "minecraft:air",
    "minecraft:air"
  ],
  [
    "minecraft:crimson_forest",
    [],
    [],
    [
      "rankine:purple_porphyry",
      "rankine:purple_porphyry",
      "rankine:purple_porphyry",
      "rankine:purple_porphyry",
      "rankine:komatiite",
      "rankine:komatiite",
      "rankine:komatiite",
      "rankine:red_porphyry"
    ],
    [],
    "rankine:dark_gravel",
    "minecraft:air",
    "minecraft:air"
  ],
  [
    "minecraft:warped_forest",
    [],
    [],
    [
      "rankine:lherzolite",
      "rankine:lherzolite",
      "rankine:lherzolite",
      "rankine:lherzolite",
      "rankine:pyroxenite",
      "rankine:pyroxenite",
      "rankine:pyroxenite",
      "rankine:harzburgite"
    ],
    [],
    "rankine:dark_gravel",
    "minecraft:air",
    "minecraft:air"
  ],
  [
    "minecraft:nether_wastes",
    [],
    [],
    [],
    [],
    "rankine:dark_gravel",
    "minecraft:air",
    "minecraft:air"
  ],
  [
    "none",
    [
      "rankine:sandy_loam",
      "rankine:sandy_loam",
      "rankine:sandy_clay_loam",
      "rankine:sandy_clay_loam",
      "rankine:sandy_clay_loam",
      "rankine:sandy_clay"
    ],
    [],
    [
      "rankine:wadsleyone",
      "rankine:troctolite",
      "rankine:gabbro",
      "rankine:slate",
      "rankine:shale",
      "rankine:tholeiitic_basalt"
    ],
    ["rankine:short_grass|70", "minecraft:grass|10"],
    "rankine:dark_gravel",
    "minecraft:air",
    "minecraft:air"
  ],
  [
    "mushroom",
    [
      "rankine:humus",
      "rankine:humus",
      "rankine:clay_loam",
      "rankine:clay_loam",
      "rankine:clay_loam",
      "rankine:clay_loam"
    ],
    [],
    [
      "rankine:wadsleyone",
      "rankine:troctolite",
      "rankine:gabbro",
      "rankine:tholeiitic_basalt",
      "rankine:marlstone"
    ],
    [
      "rankine:short_grass|70",
      "minecraft:grass|10",
      "minecraft:red_mushroom|10",
      "minecraft:brown_mushroom|10",
      "rankine:crimson_clover|10"
    ],
    "rankine:light_gravel",
    "minecraft:air",
    "minecraft:air"
  ],
  [
    "ocean",
    [
      "rankine:sandy_clay_loam",
      "rankine:sandy_clay_loam",
      "rankine:sandy_clay",
      "rankine:silty_clay_loam",
      "rankine:silty_clay_loam",
      "rankine:silty_clay"
    ],
    [],
    [
      "rankine:wadsleyone",
      "rankine:troctolite",
      "rankine:gabbro",
      "rankine:tholeiitic_basalt"
    ],
    ["rankine:short_grass|70", "minecraft:grass|10"],
    "rankine:light_gravel",
    "minecraft:air",
    "minecraft:air"
  ],
  [
    "beach",
    [
      "rankine:sandy_loam",
      "rankine:sandy_loam",
      "rankine:sandy_clay_loam",
      "rankine:sandy_clay_loam",
      "rankine:sandy_clay_loam",
      "rankine:sandy_clay"
    ],
    [],
    [
      "rankine:wadsleyone",
      "rankine:troctolite",
      "rankine:gabbro",
      "rankine:tholeiitic_basalt",
      "rankine:chalk",
      "rankine:shale",
      "rankine:marlstone"
    ],
    [
      "rankine:short_grass|70",
      "minecraft:grass|10",
      "rankine:yellow_clover|10",
      "rankine:stinging_nettle|1"
    ],
    "rankine:light_gravel",
    "minecraft:air",
    "minecraft:air"
  ],
  [
    "river",
    [
      "rankine:clay_loam",
      "rankine:clay_loam",
      "rankine:silty_clay",
      "rankine:silty_clay_loam",
      "rankine:silty_clay_loam",
      "rankine:silty_clay"
    ],
    [],
    [
      "rankine:post_perovskite",
      "rankine:troctolite",
      "rankine:gabbro",
      "rankine:tholeiitic_basalt",
      "rankine:chalk",
      "rankine:shale",
      "rankine:shale",
      "rankine:anorthosite"
    ],
    [
      "rankine:short_grass|20",
      "minecraft:grass|50",
      "rankine:stinging_nettle|1"
    ],
    "minecraft:air",
    "rankine:silt",
    "minecraft:air"
  ],
  [
    "savanna",
    [
      "rankine:silty_loam",
      "rankine:silty_loam",
      "rankine:silty_clay_loam",
      "rankine:sandy_loam",
      "rankine:sandy_loam",
      "rankine:sandy_clay_loam"
    ],
    [],
    [
      "rankine:rose_marble",
      "rankine:red_dacite",
      "rankine:rhyolite",
      "rankine:quartzite",
      "rankine:siltstone",
      "rankine:graywacke"
    ],
    [
      "rankine:short_grass|70",
      "minecraft:grass|10",
      "rankine:yellow_clover|10",
      "rankine:white_clover|10",
      "rankine:stinging_nettle|1"
    ],
    "rankine:light_gravel",
    "minecraft:air",
    "minecraft:air"
  ],
  [
    "mesa",
    [
      "rankine:silty_loam",
      "rankine:silty_loam",
      "rankine:silty_clay_loam",
      "rankine:silty_loam",
      "rankine:silty_loam",
      "rankine:silty_clay_loam"
    ],
    [],
    [
      "rankine:bridgmanham",
      "rankine:rose_marble",
      "rankine:red_dacite",
      "rankine:rhyolite",
      "rankine:quartzite",
      "rankine:siltstone",
      "rankine:arkose"
    ],
    [
      "rankine:short_grass|70",
      "minecraft:grass|10",
      "rankine:yellow_clover|10",
      "rankine:stinging_nettle|1"
    ],
    "rankine:light_gravel",
    "minecraft:air",
    "minecraft:air"
  ],
  [
    "desert",
    [
      "rankine:loamy_sand",
      "rankine:loamy_sand",
      "rankine:loamy_sand",
      "rankine:loamy_sand",
      "rankine:loamy_sand",
      "rankine:loamy_sand"
    ],
    [],
    [
      "rankine:bridgmanham",
      "rankine:rose_marble",
      "rankine:red_dacite",
      "rankine:rhyolite",
      "rankine:quartzite",
      "rankine:siltstone",
      "rankine:itacolumite"
    ],
    [
      "rankine:short_grass|30",
      "minecraft:dead_bush|10",
      "rankine:stinging_nettle|1"
    ],
    "rankine:light_gravel",
    "rankine:desert_sand",
    "rankine:desert_sandstone"
  ],
  [
    "extreme_hills",
    [
      "rankine:sandy_loam",
      "rankine:sandy_loam",
      "rankine:sandy_clay_loam",
      "rankine:loamy_sand",
      "rankine:loamy_sand",
      "rankine:sandy_clay_loam"
    ],
    [],
    [
      "rankine:ringwoodine",
      "rankine:serpentinite",
      "rankine:greenschist",
      "rankine:mariposite",
      "rankine:gray_marble",
      "rankine:dolostone",
      "rankine:gneiss",
      "rankine:anorthosite",
      "rankine:hornblende_andesite"
    ],
    [
      "rankine:short_grass|70",
      "minecraft:grass|10",
      "rankine:red_clover|10",
      "rankine:white_clover|10",
      "rankine:stinging_nettle|1"
    ],
    "minecraft:air",
    "minecraft:air",
    "minecraft:air"
  ],
  [
    "forest",
    [
      "rankine:loam",
      "rankine:loam",
      "rankine:clay_loam",
      "rankine:sandy_loam",
      "rankine:sandy_loam",
      "rankine:sandy_clay_loam"
    ],
    [],
    [
      "rankine:sommanite",
      "rankine:black_dacite",
      "rankine:comendite",
      "rankine:black_marble",
      "rankine:soapstone",
      "rankine:anorthosite",
      "rankine:limestone"
    ],
    [
      "rankine:short_grass|70",
      "minecraft:grass|10",
      "rankine:yellow_clover|10",
      "rankine:white_clover|10",
      "rankine:stinging_nettle|1"
    ],
    "minecraft:air",
    "minecraft:air",
    "minecraft:air"
  ],
  [
    "taiga",
    [
      "rankine:sandy_loam",
      "rankine:sandy_loam",
      "rankine:sandy_clay_loam",
      "rankine:loamy_sand",
      "rankine:loamy_sand",
      "rankine:sandy_clay_loam"
    ],
    [],
    [
      "rankine:sommanite",
      "rankine:black_dacite",
      "rankine:comendite",
      "rankine:white_marble",
      "rankine:soapstone",
      "rankine:anorthosite",
      "rankine:dolostone"
    ],
    [
      "rankine:short_grass|70",
      "minecraft:fern|10",
      "rankine:red_clover|10",
      "rankine:white_clover|10",
      "rankine:stinging_nettle|1"
    ],
    "minecraft:air",
    "minecraft:air",
    "minecraft:air"
  ],
  [
    "plains",
    [
      "rankine:sandy_loam",
      "rankine:sandy_loam",
      "rankine:sandy_clay_loam",
      "rankine:sandy_clay_loam",
      "rankine:sandy_clay_loam",
      "rankine:clay_loam"
    ],
    [],
    [
      "rankine:bridgmanham",
      "rankine:red_dacite",
      "rankine:rhyolite",
      "rankine:gray_marble",
      "rankine:anorthosite",
      "rankine:limestone",
      "rankine:siltstone"
    ],
    [
      "rankine:short_grass|70",
      "minecraft:grass|10",
      "rankine:crimson_clover|10",
      "rankine:white_clover|10",
      "rankine:stinging_nettle|1"
    ],
    "minecraft:air",
    "minecraft:air",
    "minecraft:air"
  ],
  [
    "icy",
    [
      "rankine:silty_loam",
      "rankine:silty_loam",
      "rankine:permafrost",
      "rankine:silty_clay_loam",
      "rankine:silty_clay_loam",
      "rankine:permafrost"
    ],
    [],
    [
      "rankine:whiteschist",
      "rankine:white_marble",
      "rankine:comendite",
      "rankine:mica_schist",
      "rankine:phyllite",
      "minecraft:andesite",
      "rankine:chalk"
    ],
    [
      "rankine:short_grass|70",
      "minecraft:fern|10",
      "rankine:red_clover|10",
      "rankine:white_clover|10",
      "rankine:stinging_nettle|1"
    ],
    "minecraft:air",
    "minecraft:air",
    "minecraft:air"
  ],
  [
    "jungle",
    [
      "rankine:humus",
      "rankine:humus",
      "rankine:laterite",
      "rankine:clay_loam",
      "rankine:clay_loam",
      "rankine:laterite"
    ],
    [],
    [
      "rankine:whiteschist",
      "rankine:eclogite",
      "rankine:gneiss",
      "rankine:mica_schist",
      "rankine:phyllite",
      "rankine:slate",
      "rankine:mudstone"
    ],
    [
      "rankine:short_grass|70",
      "minecraft:grass|10",
      "rankine:crimson_clover|10",
      "rankine:yellow_clover|10",
      "rankine:stinging_nettle|1"
    ],
    "rankine:dark_gravel",
    "minecraft:air",
    "minecraft:air"
  ],
  [
    "swamp",
    [
      "rankine:loam",
      "rankine:loam",
      "rankine:clay_loam",
      "rankine:humus",
      "rankine:humus",
      "rankine:clay_loam"
    ],
    [],
    [
      "rankine:post_perovskite",
      "rankine:eclogite",
      "rankine:gneiss",
      "rankine:mica_schist",
      "rankine:phyllite",
      "rankine:slate",
      "rankine:mudstone"
    ],
    [
      "rankine:short_grass|70",
      "minecraft:grass|10",
      "rankine:red_clover|10",
      "rankine:stinging_nettle|1"
    ],
    "rankine:dark_gravel",
    "minecraft:air",
    "minecraft:air"
  ]
]