
[TileBlockConfig]
	#If grass bed can sleep
	sleep = false
	#If Drying rack need daytime
	"need daytime" = false
	#Infinity water biomes
	infinityWaterSourceBiomeList = ["minecraft:deep_cold_ocean", "minecraft:frozen_river", "minecraft:warm_ocean", "minecraft:ocean", "minecraft:frozen_ocean", "minecraft:deep_frozen_ocean", "minecraft:river", "minecraft:deep_ocean", "minecraft:deep_warm_ocean", "minecraft:deep_lukewarm_ocean", "minecraft:lukewarm_ocean", "minecraft:cold_ocean"]
	"Infinity water" = false

