
[Display]
	# 
	#It decides if player can see items' water level.
	#决定玩家是否可一查看物品的水分值。默认：true
	#Default:true
	displayFoodsWaterLevel = true
	# 
	#Open debug mode.
	#开启调试模式。默认：false
	#Default:false
	debugMode = false
	# 
	#It decides if player can see water saturation level.
	#决定玩家是否可以看到饱和水分值。默认：false
	#Default:false
	displayWaterSaturationLevel = false

